//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xaydung.Resrouce.XML {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xaydung.Resrouce.XML.HomeText", typeof(HomeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tài chính hàng năm.
        /// </summary>
        internal static string Bao_cao_chinh_hang_nam {
            get {
                return ResourceManager.GetString("Bao_cao_chinh_hang_nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các nhà đầu tư, cổ đông.
        /// </summary>
        internal static string Cac_nha_dau_tu {
            get {
                return ResourceManager.GetString("Cac_nha_dau_tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ xử lý nước cấp.
        /// </summary>
        internal static string Cong_nghe_xu_ly_nuoc_cap {
            get {
                return ResourceManager.GetString("Cong_nghe_xu_ly_nuoc_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ xử lý nước thải.
        /// </summary>
        internal static string Cong_nghe_xu_ly_nuoc_thai {
            get {
                return ResourceManager.GetString("Cong_nghe_xu_ly_nuoc_thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string Dich_vu {
            get {
                return ResourceManager.GetString("Dich_vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR(Đối tác).
        /// </summary>
        internal static string Doi_tac {
            get {
                return ResourceManager.GetString("Doi_tac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án công trình.
        /// </summary>
        internal static string Du_an_cong_trinh {
            get {
                return ResourceManager.GetString("Du_an_cong_trinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string Gioi_thieu {
            get {
                return ResourceManager.GetString("Gioi_thieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu sơ lược về công ty damifa.
        /// </summary>
        internal static string Gioi_thieu_so_luoc_cong_ty {
            get {
                return ResourceManager.GetString("Gioi_thieu_so_luoc_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string Lien_he {
            get {
                return ResourceManager.GetString("Lien_he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lời chào của lãnh đạo.
        /// </summary>
        internal static string Loi_chao_cua_lanh_dao {
            get {
                return ResourceManager.GetString("Loi_chao_cua_lanh_dao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năng lực tài chinh công ty.
        /// </summary>
        internal static string Nang_luc_tai_chinh_cong_ty {
            get {
                return ResourceManager.GetString("Nang_luc_tai_chinh_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng Cáo.
        /// </summary>
        internal static string Quang_cao {
            get {
                return ResourceManager.GetString("Quang_cao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sơ đồ tổ chức.
        /// </summary>
        internal static string So_do_to_chuc {
            get {
                return ResourceManager.GetString("So_do_to_chuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        internal static string Tin_tuc {
            get {
                return ResourceManager.GetString("Tin_tuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm thông tin.
        /// </summary>
        internal static string Trung_tam_cong_ty {
            get {
                return ResourceManager.GetString("Trung_tam_cong_ty", resourceCulture);
            }
        }
    }
}
