//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xaydung
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddingNo
    {
        public Nullable<long> NO { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Place { get; set; }
        public string Year { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
